<a href="https://colab.research.google.com/github/IrumShehryar/ML-NLP-Coursework/blob/main/machine-learning/Project06_Feature_Engineering_by_Window_Method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Creating Data

In [2]:
X = np.linspace(1,5,10).round(1)

In [3]:
X

array([1. , 1.4, 1.9, 2.3, 2.8, 3.2, 3.7, 4.1, 4.6, 5. ])

In [4]:
X.shape

(10,)

In [5]:
y = np.arange(0,10)

In [6]:
y.shape

(10,)

In [7]:
data = pd.DataFrame({'X': X, 'y' : y})

In [8]:
data

     X  y
0  1.0  0
1  1.4  1
2  1.9  2
3  2.3  3
4  2.8  4
5  3.2  5
6  3.7  6
7  4.1  7
8  4.6  8
9  5.0  9

# Creating New Features using window

In [9]:
win = 2

features = data['X']
label = data['y']

In [10]:
features

0    1.0
1    1.4
2    1.9
3    2.3
4    2.8
5    3.2
6    3.7
7    4.1
8    4.6
9    5.0
Name: X, dtype: float64

In [11]:
X_Min=[]
X_Max=[]
X_Mean=[]
X_Std=[]

labels=[]

for i in range(len(data) - win):

    X = features[i:i+win]
    y = label[i+win]
    labels.append(y)

    X_Min.append(np.min(X))
    X_Max.append(np.max(X))
    X_Mean.append(np.mean(X))
    X_Std.append(np.std(X))

In [21]:
i = 2
features[i:i+win]

2    1.9
3    2.3
Name: X, dtype: float64

In [22]:
label[i+win]

np.int64(4)

# Create dataframe from features

In [23]:
df_features = pd.DataFrame({'X_Min': X_Min, 'X_Max': X_Max, 'X_Mean': X_Mean, 'X_Std': X_Std,'labels':labels})

In [24]:
df_features

   X_Min  X_Max  X_Mean  X_Std  labels
0    1.0    1.4    1.20   0.20       2
1    1.4    1.9    1.65   0.25       3
2    1.9    2.3    2.10   0.20       4
3    2.3    2.8    2.55   0.25       5
4    2.8    3.2    3.00   0.20       6
5    3.2    3.7    3.45   0.25       7
6    3.7    4.1    3.90   0.20       8
7    4.1    4.6    4.35   0.25       9