<a href="https://colab.research.google.com/github/IrumShehryar/ML-NLP-Coursework/blob/main/nlp/02-text-vectorization/Project01_Creating_one_hot_encoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [ ]:
import numpy as np
import pandas as pd

# Generate a sentence

In [ ]:
sentence = "The quick and cute white cat jumps over the lazy rabbit"

# Get the vocabsize

In [ ]:
set(sentence.lower().split(' ')) # set will take the unique value

{'and',
 'cat',
 'cute',
 'jumps',
 'lazy',
 'over',
 'quick',
 'rabbit',
 'the',
 'white'}

In [ ]:
set(sentence.lower().split(' '))

{'and',
 'cat',
 'cute',
 'jumps',
 'lazy',
 'over',
 'quick',
 'rabbit',
 'the',
 'white'}

In [ ]:
vocab = list(set(sentence.lower().split(' ')))

In [ ]:
vocab=list(set(sentence.lower().split(' ')))

In [ ]:
vocab.sort()

In [ ]:
vocab.sort()

In [ ]:
vocab

['and',
 'cat',
 'cute',
 'jumps',
 'lazy',
 'over',
 'quick',
 'rabbit',
 'the',
 'white']

# Creating One hot encoder

In [ ]:
pd.DataFrame(np.identity(len(vocab)), index = vocab, columns = vocab) # identity matrix

        and  cat  cute  jumps  lazy  over  quick  rabbit  the  white
and     1.0  0.0   0.0    0.0   0.0   0.0    0.0     0.0  0.0    0.0
cat     0.0  1.0   0.0    0.0   0.0   0.0    0.0     0.0  0.0    0.0
cute    0.0  0.0   1.0    0.0   0.0   0.0    0.0     0.0  0.0    0.0
jumps   0.0  0.0   0.0    1.0   0.0   0.0    0.0     0.0  0.0    0.0
lazy    0.0  0.0   0.0    0.0   1.0   0.0    0.0     0.0  0.0    0.0
over    0.0  0.0   0.0    0.0   0.0   1.0    0.0     0.0  0.0    0.0
quick   0.0  0.0   0.0    0.0   0.0   0.0    1.0     0.0  0.0    0.0
rabbit  0.0  0.0   0.0    0.0   0.0   0.0    0.0     1.0  0.0    0.0
the     0.0  0.0   0.0    0.0   0.0   0.0    0.0     0.0  1.0    0.0
white   0.0  0.0   0.0    0.0   0.0   0.0    0.0     0.0  0.0    1.0

In [ ]:
pd.DataFrame(np.identity(len(vocab)),index=vocab,columns=vocab)

        and  cat  cute  jumps  lazy  over  quick  rabbit  the  white
and     1.0  0.0   0.0    0.0   0.0   0.0    0.0     0.0  0.0    0.0
cat     0.0  1.0   0.0    0.0   0.0   0.0    0.0     0.0  0.0    0.0
cute    0.0  0.0   1.0    0.0   0.0   0.0    0.0     0.0  0.0    0.0
jumps   0.0  0.0   0.0    1.0   0.0   0.0    0.0     0.0  0.0    0.0
lazy    0.0  0.0   0.0    0.0   1.0   0.0    0.0     0.0  0.0    0.0
over    0.0  0.0   0.0    0.0   0.0   1.0    0.0     0.0  0.0    0.0
quick   0.0  0.0   0.0    0.0   0.0   0.0    1.0     0.0  0.0    0.0
rabbit  0.0  0.0   0.0    0.0   0.0   0.0    0.0     1.0  0.0    0.0
the     0.0  0.0   0.0    0.0   0.0   0.0    0.0     0.0  1.0    0.0
white   0.0  0.0   0.0    0.0   0.0   0.0    0.0     0.0  0.0    1.0