<a href="https://colab.research.google.com/github/IrumShehryar/ML-NLP-Coursework/blob/main/machine-learning/Project03_Dealing_With_Missing_Values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Generating data using pandas

In [2]:
df = pd.DataFrame({"name":["William","Emma","Sofia","Markus","Edward","Thomas","Ethan","Olivia","Arun","Anika","Paulo"]
,"region":["East",np.nan,"East","South","West","West","South","West","West","East","South"]
,"sales":[50000,52000,90000,np.nan,42000,72000,49000,np.nan,67000,65000,67000]
,"expenses":[42000,43000,np.nan,44000,38000,39000,42000,np.nan,39000,44000,45000]
,"lossValues":[12000,'?','?',np.nan,11000,33000,44000,10000,22000,30000,99000]})

df

       name region    sales  expenses lossValues
0   William   East  50000.0   42000.0      12000
1      Emma    NaN  52000.0   43000.0          ?
2     Sofia   East  90000.0       NaN          ?
3    Markus  South      NaN   44000.0        NaN
4    Edward   West  42000.0   38000.0      11000
5    Thomas   West  72000.0   39000.0      33000
6     Ethan  South  49000.0   42000.0      44000
7    Olivia   West      NaN       NaN      10000
8      Arun   West  67000.0   39000.0      22000
9     Anika   East  65000.0   44000.0      30000
10    Paulo  South  67000.0   45000.0      99000

## Information about data

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        11 non-null     object
 1   region      10 non-null     object
 2   sales       9 non-null      float64
 3   expenses    9 non-null      float64
 4   lossValues  10 non-null     object
dtypes: float64(2), object(3)
memory usage: 572.0+ bytes

## Finding missing or null values

In [4]:
df.isnull()

     name  region  sales  expenses  lossValues
0   False   False  False     False       False
1   False    True  False     False       False
2   False   False  False      True       False
3   False   False   True     False        True
4   False   False  False     False       False
5   False   False  False     False       False
6   False   False  False     False       False
7   False   False   True      True       False
8   False   False  False     False       False
9   False   False  False     False       False
10  False   False  False     False       False

In [5]:
df.isnull().any()

name          False
region         True
sales          True
expenses       True
lossValues     True
dtype: bool

In [6]:
df.isnull().sum()

name          0
region        1
sales         2
expenses      2
lossValues    1
dtype: int64

## Replacing "?" with a null value

In [9]:
df.replace(to_replace ='?', value = np.nan, inplace = True)

/tmp/ipykernel_15302/960218073.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(to_replace ='?', value = np.nan, inplace = True)

In [7]:
df.replace(to_replace='?',value=np.nan)

/tmp/ipykernel_15302/1118707568.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(to_replace='?',value=np.nan)

       name region    sales  expenses  lossValues
0   William   East  50000.0   42000.0     12000.0
1      Emma    NaN  52000.0   43000.0         NaN
2     Sofia   East  90000.0       NaN         NaN
3    Markus  South      NaN   44000.0         NaN
4    Edward   West  42000.0   38000.0     11000.0
5    Thomas   West  72000.0   39000.0     33000.0
6     Ethan  South  49000.0   42000.0     44000.0
7    Olivia   West      NaN       NaN     10000.0
8      Arun   West  67000.0   39000.0     22000.0
9     Anika   East  65000.0   44000.0     30000.0
10    Paulo  South  67000.0   45000.0     99000.0

In [10]:
df

       name region    sales  expenses  lossValues
0   William   East  50000.0   42000.0     12000.0
1      Emma    NaN  52000.0   43000.0         NaN
2     Sofia   East  90000.0       NaN         NaN
3    Markus  South      NaN   44000.0         NaN
4    Edward   West  42000.0   38000.0     11000.0
5    Thomas   West  72000.0   39000.0     33000.0
6     Ethan  South  49000.0   42000.0     44000.0
7    Olivia   West      NaN       NaN     10000.0
8      Arun   West  67000.0   39000.0     22000.0
9     Anika   East  65000.0   44000.0     30000.0
10    Paulo  South  67000.0   45000.0     99000.0

## Creating copy of df

In [11]:
df1 = df.copy()
df1

       name region    sales  expenses  lossValues
0   William   East  50000.0   42000.0     12000.0
1      Emma    NaN  52000.0   43000.0         NaN
2     Sofia   East  90000.0       NaN         NaN
3    Markus  South      NaN   44000.0         NaN
4    Edward   West  42000.0   38000.0     11000.0
5    Thomas   West  72000.0   39000.0     33000.0
6     Ethan  South  49000.0   42000.0     44000.0
7    Olivia   West      NaN       NaN     10000.0
8      Arun   West  67000.0   39000.0     22000.0
9     Anika   East  65000.0   44000.0     30000.0
10    Paulo  South  67000.0   45000.0     99000.0

## Fill NaN with a value = 10000

In [12]:
df1.fillna(10000)

       name region    sales  expenses  lossValues
0   William   East  50000.0   42000.0     12000.0
1      Emma  10000  52000.0   43000.0     10000.0
2     Sofia   East  90000.0   10000.0     10000.0
3    Markus  South  10000.0   44000.0     10000.0
4    Edward   West  42000.0   38000.0     11000.0
5    Thomas   West  72000.0   39000.0     33000.0
6     Ethan  South  49000.0   42000.0     44000.0
7    Olivia   West  10000.0   10000.0     10000.0
8      Arun   West  67000.0   39000.0     22000.0
9     Anika   East  65000.0   44000.0     30000.0
10    Paulo  South  67000.0   45000.0     99000.0

In [13]:
df1

       name region    sales  expenses  lossValues
0   William   East  50000.0   42000.0     12000.0
1      Emma    NaN  52000.0   43000.0         NaN
2     Sofia   East  90000.0       NaN         NaN
3    Markus  South      NaN   44000.0         NaN
4    Edward   West  42000.0   38000.0     11000.0
5    Thomas   West  72000.0   39000.0     33000.0
6     Ethan  South  49000.0   42000.0     44000.0
7    Olivia   West      NaN       NaN     10000.0
8      Arun   West  67000.0   39000.0     22000.0
9     Anika   East  65000.0   44000.0     30000.0
10    Paulo  South  67000.0   45000.0     99000.0

## Fill the Nan Values of df1['region'] with a word 'NEWS'

In [14]:
df1['region'].fillna(value='News',inplace=True)

/tmp/ipykernel_15302/3792761844.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['region'].fillna(value='News',inplace=True)

In [17]:
df1['region'].fillna(value = 'NEWS',inplace = True)

/tmp/ipykernel_15302/850146590.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['region'].fillna(value = 'NEWS',inplace = True)

In [18]:
df1

       name region    sales  expenses  lossValues
0   William   East  50000.0   42000.0     12000.0
1      Emma   News  52000.0   43000.0         NaN
2     Sofia   East  90000.0       NaN         NaN
3    Markus  South      NaN   44000.0         NaN
4    Edward   West  42000.0   38000.0     11000.0
5    Thomas   West  72000.0   39000.0     33000.0
6     Ethan  South  49000.0   42000.0     44000.0
7    Olivia   West      NaN       NaN     10000.0
8      Arun   West  67000.0   39000.0     22000.0
9     Anika   East  65000.0   44000.0     30000.0
10    Paulo  South  67000.0   45000.0     99000.0

## Fill the NaN values of column sales with the mean of column, expenses with median of
## column expenses and loss value with the standard deviation of the column loss values

In [ ]:
df1.fillna(value = {'sales' : df1['sales'].mean(), 'expenses' : df1['expenses'].median(), 'lossValues' : df1['lossValues'].std()}, inplace = True )

In [21]:
df1.fillna(value={'sales': df1['sales'].mean(),'expenses':df1['expenses'].median(),'lossValues':df1['lossValues'].std()},inplace=True)

In [22]:
df1

       name region         sales  expenses    lossValues
0   William   East  50000.000000   42000.0  12000.000000
1      Emma   News  52000.000000   43000.0  29422.719598
2     Sofia   East  90000.000000   42000.0  29422.719598
3    Markus  South  61555.555556   44000.0  29422.719598
4    Edward   West  42000.000000   38000.0  11000.000000
5    Thomas   West  72000.000000   39000.0  33000.000000
6     Ethan  South  49000.000000   42000.0  44000.000000
7    Olivia   West  61555.555556   42000.0  10000.000000
8      Arun   West  67000.000000   39000.0  22000.000000
9     Anika   East  65000.000000   44000.0  30000.000000
10    Paulo  South  67000.000000   45000.0  99000.000000