<a href="https://colab.research.google.com/github/IrumShehryar/ML-NLP-Coursework/blob/main/machine-learning/Project04_Dealing_with_Categorical_Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [5]:
data_url = 'http://vincentarelbundock.github.io/Rdatasets/csv/carData/Salaries.csv'
df = pd.read_csv(data_url,index_col=0)
df.head(10)
df

              rank discipline  yrs.since.phd  yrs.service   sex  salary
rownames
1             Prof          B             19           18  Male  139750
2             Prof          B             20           16  Male  173200
3         AsstProf          B              4            3  Male   79750
4             Prof          B             45           39  Male  115000
5             Prof          B             40           41  Male  141500
...            ...        ...            ...          ...   ...     ...
393           Prof          A             33           30  Male  103106
394           Prof          A             31           19  Male  150564
395           Prof          A             42           25  Male  101738
396           Prof          A             25           15  Male   95329
397       AsstProf          A              8            4  Male   81035

[397 rows x 6 columns]

In [6]:
df_dummies=pd.get_dummies(df['rank'])
df_dummies

          AssocProf  AsstProf   Prof
rownames
1             False     False   True
2             False     False   True
3             False      True  False
4             False     False   True
5             False     False   True
...             ...       ...    ...
393           False     False   True
394           False     False   True
395           False     False   True
396           False     False   True
397           False      True  False

[397 rows x 3 columns]

In [ ]:
df_dummies = pd.get_dummies(df['rank'])
df_dummies

In [ ]:
df_dummies = pd.get_dummies(df[['rank','sex']])
df_dummies

In [7]:
df_dummies=pd.get_dummies(df[['rank','sex']])
df_dummies

          rank_AssocProf  rank_AsstProf  rank_Prof  sex_Female  sex_Male
rownames
1                  False          False       True       False      True
2                  False          False       True       False      True
3                  False           True      False       False      True
4                  False          False       True       False      True
5                  False          False       True       False      True
...                  ...            ...        ...         ...       ...
393                False          False       True       False      True
394                False          False       True       False      True
395                False          False       True       False      True
396                False          False       True       False      True
397                False           True      False       False      True

[397 rows x 5 columns]

In [8]:
df_dummies = pd.get_dummies(df[['rank','sex','discipline']],prefix = '', prefix_sep ='')
df_dummies.head(10)

          AssocProf  AsstProf   Prof  Female   Male      A     B
rownames
1             False     False   True   False   True  False  True
2             False     False   True   False   True  False  True
3             False      True  False   False   True  False  True
4             False     False   True   False   True  False  True
5             False     False   True   False   True  False  True
6              True     False  False   False   True  False  True
7             False     False   True   False   True  False  True
8             False     False   True   False   True  False  True
9             False     False   True   False   True  False  True
10            False     False   True    True  False  False  True

In [9]:
df_dummies = pd.get_dummies(df[['rank','sex','discipline']],prefix = '', prefix_sep ='', drop_first=True)
df_dummies.head()

          AsstProf   Prof  Male     B
rownames
1            False   True  True  True
2            False   True  True  True
3             True  False  True  True
4            False   True  True  True
5            False   True  True  True

In [10]:
df2 = pd.concat([df,df_dummies], axis = 1)
df2

,rank,discipline,yrs.since.phd,yrs.service,sex,salary,AsstProf,Prof,Male,B
rownames,,,,,,,,,,
1,Prof,B,19,18,Male,139750,False,True,True,True
2,Prof,B,20,16,Male,173200,False,True,True,True
3,AsstProf,B,4,3,Male,79750,True,False,True,True
4,Prof,B,45,39,Male,115000,False,True,True,True
5,Prof,B,40,41,Male,141500,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...
393,Prof,A,33,30,Male,103106,False,True,True,False
394,Prof,A,31,19,Male,150564,False,True,True,False
395,Prof,A,42,25,Male,101738,False,True,True,False
396,Prof,A,25,15,Male,95329,False,True,True,False
397,AsstProf,A,8,4,Male,81035,True,False,True,False

# Drop rank, sex and discipline columns because their dummy variables have already been created

In [11]:
df2.drop(['rank','sex','discipline'], axis = 1, inplace = True)

In [12]:
df2

          yrs.since.phd  yrs.service  salary  AsstProf   Prof  Male      B
rownames
1                    19           18  139750     False   True  True   True
2                    20           16  173200     False   True  True   True
3                     4            3   79750      True  False  True   True
4                    45           39  115000     False   True  True   True
5                    40           41  141500     False   True  True   True
...                 ...          ...     ...       ...    ...   ...    ...
393                  33           30  103106     False   True  True  False
394                  31           19  150564     False   True  True  False
395                  42           25  101738     False   True  True  False
396                  25           15   95329     False   True  True  False
397                   8            4   81035      True  False  True  False

[397 rows x 7 columns]

In [13]:
X = df2.drop(['salary'], axis = 1).values

In [14]:
X

array([[19, 18, False, True, True, True],
       [20, 16, False, True, True, True],
       [4, 3, True, False, True, True],
       ...,
       [42, 25, False, True, True, False],
       [25, 15, False, True, True, False],
       [8, 4, True, False, True, False]], dtype=object)

In [15]:
y = df2['salary']

In [16]:
y

rownames
1      139750
2      173200
3       79750
4      115000
5      141500
        ...
393    103106
394    150564
395    101738
396     95329
397     81035
Name: salary, Length: 397, dtype: int64

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)